[package]
name = "tokio-multithread"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
[dependencies.futures]
version = "0.3.19"
default-features = false
features = ["thread-pool"]
